---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
requirements:
  requiredStorage:      12
  requiredRam:          2.0
  internetCheckUrl:     ""
  check:
    - storage
    - ram
    - root
    - screen
