# Главные переменные проекта.
# Меняешь здесь — потом используешь sed/скрипты для переименования.
DISTRO_ID="shevos"
DISTRO_NAME="ShevOS"
DISTRO_LABEL="SHEVOS"
DISTRO_PUBLISHER="ShevOS Project"
DISTRO_TIMEZONE="Europe/Moscow"
DISTRO_LOCALE="ru_RU.UTF-8"
DISTRO_FALLBACK_LOCALE="en_US.UTF-8"
DISTRO_KEYMAP_CONSOLE="ru"
DISTRO_XKB_LAYOUTS="us,ru"
DISTRO_XKB_OPTIONS="grp:alt_shift_toggle"
