# pacman.conf для сборки ISO ShevOS.
# mkarchiso использует этот файл для установки пакетов в live-образ.

[options]
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
HoldPkg = pacman glibc

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Локальный репозиторий для пакетов, которых нет в официальном Arch.
# build.sh копирует содержимое archiso/localrepo в /tmp/shevos-localrepo.
# В первую очередь тут лежит пакет calamares, собранный из AUR обычным пользователем.
[shevos-local]
SigLevel = Optional TrustAll
Server = file:///tmp/shevos-localrepo/os/$arch
