---
efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - file
  - small
  - suspend
drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
  - "f2fs"
initialPartitioningChoice: "erase"
